### ISSUE TITLE
Compatibility with Ruby 1.8.7 

### ISSUE THREAD

**Issue by ecleel** [stouset/twitter_bootstrap_form_for#14]
Hi,
your gem save my time. I Appreciate your work.

**bootstrap_form** doesn't work with Ruby 1.8.7 because you use new lambda syntax [-> in form_builder ](https://github.com/stouset/twitter_bootstrap_form_for/blob/master/lib/twitter_bootstrap_form_for/form_builder.rb#L33) .
Also, I have other error [here with *](https://github.com/stouset/twitter_bootstrap_form_for/blob/master/lib/twitter_bootstrap_form_for/form_builder.rb#L14-16).

I am using **ree-1.8.7-2010.02** with **Rails 3.0.10**

Thanks

**Comment by stouset** [comment]
Good catch.

**Comment by stouset** [comment]
1.0.2 is away, with this fix.

**Comment by ecleel** [comment]
Thanks @stouset for fast fix :)
