### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pivotale20** [stouset/twitter_bootstrap_form_for#17]
What is the license for this gem? MIT?

**Comment by stouset** [comment]
Yes. Can't believe I overlooked that. :) Will put that in the repo ASAP. 

## 

Stephen Touset
stephen@touset.org

**Comment by stouset** [comment]
Fixed. 5c3e7c606fa50712067458957e82fd500a1c857b

**Comment by pivotale20** [comment]
Thanks!

**Comment by stouset** [comment]
1.0.3 has been released with this fix included.
