### ISSUE TITLE
How to support form_tag too?

### ISSUE THREAD

**Issue by millisami** [stouset/twitter_bootstrap_form_for#19]
Right now, I think this works only form `@form` resource. i.e. only with `= twitter_bootstrap_form_for @user do |user|`

Does it or how do I make it work with `form_tag` syntax as well. like `=twitter_bootstrap_form_tag :user do |user| ??

**Comment by stouset** [comment]
Rails' `form_tag` doesn't yield a `FormBuilder` block. That's the entire point of `form_for`. What, exactly, do you need to do that the current syntax doesn't support?

**Comment by millisami** [comment]
Its the case for signin/login form in a simple rails app.

``` rb
= form_tag sessions_path do
  div class="clearfix"
    = label_tag :username
    div class="input"  
      = text_field_tag :username, params[:username]

  div class="clearfix"
    = label_tag :password
    div class="input"  
      = password_field_tag :password

  div class="clearfix"
    div class="input"
      ul class="inputs-list"
        li
          label
            = check_box_tag :remember_me, 1, params[:remember_me]
            span style="padding-left: 3px;" Remember me

  div class="actions"
    input class="btn primary" name="commit" type="submit" value="Log in"
    button class="btn" name="button" type="reset" Cancel
```

In the above form, I'd to write the markup manually that matches with the bootstrap markup.

**Comment by stouset** [comment]
Supporting this kind of case would be significantly more work. Rails `FormBuilder`s assume you have access to an underlying model, and this plugin merely wraps calls to the underlying `FormBuilder` helpers.

I'd be willing to consider a patch that adds this capability.

However, I've frequently found that these "simple" forms are still best represented with an underlying model. That form sure looks like it's based off a `User` to me. What's stopping you from:

``` haml
= form_tag @user, :url => sessions_path do |user|
  = user.text_field :username
  = user.password_field :password
  = user.inputs do
    = user.check_box :remember_me
```

**Comment by millisami** [comment]
Yup, its a user login form based off https://github.com/NoamB/sorcery
Anyways, I'll try that out see what I come up with.
Thanks

**Comment by stouset** [comment]
Let me know. I'm not opposed to implementing this _per se_, but it's a decent amount of work for something that I suspect is often just a code-smell that I'd rather not encourage. :)

**Comment by stouset** [comment]
Were you able to convert the form to the objectified syntax?

**Comment by millisami** [comment]
I think that I couldn't clearify the question.

I'm trying to use the `= twitter_bootstrap_form_tag` just like `= twitter_bootstrap_form_for` so that I don't have to write the extra markup just like `= twitter_bootstrap_form_for` does.

Its not that I cannot use `= form_tag`, I can do that and the above code is working perfectly.
The question is, does `= twitter_bootstrap_form_tag` is supported or not?

**Comment by stouset** [comment]
Not currently.

It would be difficult to do correctly. Rails' `form_tag` doesn't yield to a `FormBuilder`, which is how this (and all similar plugins) are implemented. `form_tag` syntax just isn't intended to support this kind of approach. I also suspect that a `form_for` is preferential to a `form_tag` in virtually all cases.

Because of those two concerns, I'm reluctant to support this.

**Comment by stouset** [comment]
After further research, I've decided not to support this. See:

  http://www.ruby-forum.com/topic/139014
  http://stackoverflow.com/questions/1273263/rails-form-tag-form-writing-with-non-active-record-model/1273540#1273540
