### ISSUE TITLE
Nested forms support

### ISSUE THREAD

**Issue by lchojnowski** [stouset/twitter_bootstrap_form_for#22]
I think twitter_bootstrap_form_for should support nested forms too. BTW: Great piece of work!

**Comment by stouset** [comment]
Can you provide an example?

**Comment by stouset** [comment]
Also, thanks. :)

**Comment by derekprior** [comment]
Hmmm - I would assume he means the ability to create a form for an object that uses `accepts_nested_attributes_for`, but all you need for that is support for fields_for. Looks like that's already in place...

**Comment by stouset** [comment]
It is. That's why I was asking for an example — he may have a use that I hadn't foreseen.

**Comment by lchojnowski** [comment]
MY MODEL:

``` ruby
class User < ActiveRecord::Base
  has_many :companies, :dependent => :destroy
  accepts_nested_attributes_for :companies
end
```

HAML:

```
= twitter_bootstrap_form_for @user do |user|
  = user.inputs 'User' do
    = user.text_field :first_name
    = user.text_field :last_name
    = user.email_field :email
    = user.password_field :password
    = user.password_field :password_confirmation
  = user.fields_for :companies do |companies|
    = companies.inputs 'Company' do
      = companies.text_field :name
  = user.actions do
    = user.submit 'Create!'
```

And it outputs everything under User section, but Company section is not rendered.

**Comment by mikespokefire** [comment]
In your controller after doing `@user = User.new` make sure you call `@user.companies.build`. This will ensure that there are companies in the `@user` variable and it should then render in the form correctly :-)

**Comment by stouset** [comment]
Nice catch. @lukaszchojnowski, let me know if that doesn't solve your issue.

**Comment by stouset** [comment]
Closing. Will reopen if I hear otherwise.

**Comment by lchojnowski** [comment]
Fixed! Thanks!
