### ISSUE TITLE
Placeholder on errors.

### ISSUE THREAD

**Issue by rurounijones** [stouset/twitter_bootstrap_form_for#35]
If a text field has an error associated with it then I think the current placeholder behaviour leads to confusion.

The field text loses its grey colouring and becomes red, this means that the colour hinting is lost and can lead to user confusion (Especially in cases where we are validating_presence_of).

I would either: 

Keep grey colouring on placeholder text no matter what 
or
Remove placeholder text in case of errors on the field.

What do you guys think?

**Comment by stouset** [comment]
Unless I'm misunderstanding your request, this behavior is produced by the Twitter Bootstrap styles themselves and not by this gem. This gem merely generates the appropriate markup and CSS classes.

**Comment by rurounijones** [comment]
Place-holder text is created using the following code:

`= user.email_field :email, :placeholder => 'me@example.com'`

What I am suggesting is that if the field has errors (and colours cannot be changed) on it then the placholder is automatically set to nil. This reduces confusion when an end-user is, for example, told that the field cannot be blank but can see red place-holder text in the field.

**Comment by stouset** [comment]
Ah, apologies. I did misunderstand your request. :) This sounds reasonable.

**Comment by rurounijones** [comment]
I could see it being classed as a POLS violation though which was why I wanted other's opinions.
