### ISSUE TITLE
link_to styled as button renders inline in form actions block, button_to does not.

### ISSUE THREAD

**Issue by blt** [stouset/twitter_bootstrap_form_for#37]
If I have a bit of a form that looks like this

``` erb
<%= f.actions do -%>
    <%= f.submit 'Save' %>
    <%= button_to 'Delete', dashboard_memobj_path(@memobj), :class => 'btn danger', :method => :delete %>
<% end %>
```

the 'Save' button will be rendered atop the 'Delete' button. However, if I have

``` erb
<%= f.actions do -%>
    <%= f.submit 'Save' %>
    <%= link_to 'Delete', dashboard_memobj_path(@memobj), :class => 'btn danger', :method => :delete %>
<% end %>
```

The 'Save' button and 'Delete' link--styled as a button--render inline.

**Comment by stouset** [comment]
Closing this as I'm planning to merge in the [bootstrap-2.0](https://github.com/stouset/twitter_bootstrap_form_for/tree/bootstrap-2.0) branch. Please reopen if this branch does _not_ fix the issue.
