### ISSUE TITLE
Displaying errors assigned to :base?

### ISSUE THREAD

**Issue by rymohr** [stouset/twitter_bootstrap_form_for#40]
Am I doing something wrong, or does this library not handle errors added to `:base`?  The only errors that show up for me are those attached to individual attributes.

**Comment by stouset** [comment]
It doesn't currently handle them, and I don't intend to (since any way I chose might not be acceptable for some). You should be able to easily insert your own error markup for errors on `:base`, though.

**Comment by rymohr** [comment]
Thanks.  Just wanted to make sure I wasn't doing something stupid before
adding custom markup.

**Comment by stouset** [comment]
No worries. Let me know if you have any more questions.
