### ISSUE TITLE
Errors with add-ons

### ISSUE THREAD

**Issue by smidwap** [stouset/twitter_bootstrap_form_for#41]
I thought I'd seen this issue arise before here on github, but I can't find it right now, so I'm posting again.

When a validation error occurs, a red error message is displayed next to form elements, as it should be. But when the input has an add-on, then the add-on appears in the wrong place. For instance, a prepended dollar sign appears after the error message.

I uploaded a pic for reference:

http://www.smidwap.com/addon_problem.jpg

**Comment by stouset** [comment]
Closing this as I'm planning to merge in the [bootstrap-2.0](https://github.com/stouset/twitter_bootstrap_form_for/tree/bootstrap-2.0) branch. Please reopen if this branch does _not_ fix the issue.
