### ISSUE TITLE
<select> does not accept html options

### ISSUE THREAD

**Issue by fwouts** [stouset/twitter_bootstrap_form_for#45]
Correct me if I'm wrong, but in standard Rails forms, you can specify HTML options such as a class for a `<select>` element with the following syntax:

```
f.select :field, choices, {}, { :class => 'my_css_class' }
```

With twitter_bootstrap_form_for, I was expecting the syntax to be:

```
f.select :field, label, choices, {}, { :class => 'my_css_class' }
```

However that solution does not seem to work. Is that a known issue?

**Comment by fwouts** [comment]
Turns out my server was just ignoring the changes to my file, and rebooting it fixed it. Sorry about this!

**Comment by stouset** [comment]
No problem. :) Glad to hear it was resolved.
