### ISSUE TITLE
bootstrap-2.0 no method inputs

### ISSUE THREAD

**Issue by mreq** [stouset/twitter_bootstrap_form_for#51]
Great work there!

Did the syntax changed somehow? I tried upgrading to the bootstrap-2.0 branch but am getting `undefined method 'inputs' for #<TwitterBootstrapFormFor::FormBuilder:0x00000004687460>` on previously working code.

Thanks in advance.

PS: I am using rails 3.2.1

**Comment by stouset** [comment]
Yep. Check the README.md for the new syntax. Let me know if you have any problems.

Sorry for the brief reply. Away camping this weekend, so only have my cell on me.

**Comment by mreq** [comment]
Oh, I searched the wrong branch. My bad. Thanks for this great gem!

**Comment by mhuggins** [comment]
The README.md file in master is showing the `inputs` method, and I'm getting the same error.  Which README should I be looking at?

**Comment by stouset** [comment]
bootstrap-2.0 if you're using that branch.
