### ISSUE TITLE
Rails 4.0 Support

### ISSUE THREAD

**Issue by DavidAllison** [stouset/twitter_bootstrap_form_for#81]
Since `twitter_bootstrap_form_for` relies on `actionpack ~> 3` it fails to work with Rails 4.0. Any chance we can get the dependency upgraded in the gemspec?

```
Resolving dependencies............................................................
Bundler could not find compatible versions for gem "actionpack":
  In Gemfile:
    twitter_bootstrap_form_for (>= 2.0.1.0.rc1) ruby depends on
      actionpack (~> 3) ruby

    rails (>= 4.0.0) ruby depends on
      actionpack (4.0.0)
```

**Comment by stouset** [comment]
Issue a pull request and I'll be happy to merge it. :)

I honestly haven't used this plugin myself in years (the bootstrap-2.0 branch has never been officially released, as I've never actually had the chance to _use_ it with 2.0), and don't have the time to regularly maintain it.

**Comment by apfritts** [comment]
I've updated the a forked version for Rails 4 and Bootstrap 3. I'm sort of new to RoR...so comments would be appreciated!

I created pull request: https://github.com/stouset/twitter_bootstrap_form_for/pull/84

**Comment by stouset** [comment]
Thanks. I away on vacation without a laptop until the 2nd, so you'll have to wait a bit before I can merge. 

```
--
```

Stephen Touset
stephen@touset.org

**Comment by apfritts** [comment]
You go on vacation without a laptop!?!? JK. Enjoy your vacation! :)

**Comment by c22shen** [comment]
Hi, I tried to install this gem with rails 4, but this dependency issue occurred. I'm just wondering if there is an update about this? Thanks

**Comment by stouset** [comment]
#85 will close this when merged.
