### ISSUE TITLE
Move to central organisation?

### ISSUE THREAD

**Issue by manuelmeurer** [stouset/twitter_bootstrap_form_for#87]
Hi!

I am the maintainer of three gems similar to this one that make it easier to use Twitter Bootstrap in Ruby projects (https://github.com/krautcomputing/rails-bootstrap-navbar, https://github.com/krautcomputing/bootstrap-navbar, https://github.com/krautcomputing/middleman-bootstrap-navbar).

I was thinking about moving all those gems to a separate organisation (like "bootstrap-ruby") and wanted to get some feedback from other maintainers of similar gems (and the community at large) if that makes sense and if we could use this to make it easier for people to find gems to work with Bootstrap in Ruby (Rails, Sinatra, etc.)
I think it would also invite other people to contribute to those projects if they were united in a central organisation.

What do you think?
Would you be willing to move this repo to such an organisation as well?

**Comment by stouset** [comment]
This repo is more or less unmaintained, and I'm looking for another person to take over ownership.

**Comment by manuelmeurer** [comment]
Ah ok. Do you maybe want to mention that on top of the README?
I was planning to use the organisation as a kind of curated list of tools for Bootstrap and Ruby. Maybe we can include your repo when you found another maintainer?

**Comment by manuelmeurer** [comment]
There is a discussion going on between the maintainers of the two other (major) Bootstrap Rails form builders to merge efforts: potenza/bootstrap_form#28
Would you be interested in joining them? You could retire your plugin and point users to the one that hopefully comes out of the merge efforts. :smile:

**Comment by manuelmeurer** [comment]
I will close this issue for now. The other two major gems to use Bootstrap style forms in Rails have merged their efforts in the new organisation: https://github.com/bootstrap-ruby/rails-bootstrap-forms
If you're no longer looking to maintain this gem, I would recommend adding a note to the top of the README pointing the users to the rails-bootstrap-forms repo.
